services:

    everlution_tube.tube_chain:
        class: Everlution\TubeBundle\TubeChain

    everlution_tube.serializer.job_json:
        class: Everlution\TubeBundle\Serializer\DefaultJsonJobSerializer
        arguments:
            - Everlution\TubeBundle\Model\Job
