services:

    everlution_tube.serializer.job:
        class: Everlution\TubeBundle\Serializer\JMSJobSerializer
        arguments:
            - @jms_serializer
            - 'json'
            - Everlution\TubeBundle\Model\Job
